/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "slCommon.h"

extern "C" {
#include "voc.h"
}

//==============================================================================
/**
*/
class VocAudioProcessorEditor;
class VocAudioProcessor : public slProcessor
{
public:
    //==============================================================================
    VocAudioProcessor();
    ~VocAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    
    static const char* paramTenseness;
    static const char* paramConstrictionPosition;
    static const char* paramConstrictionAmount;
    static const char* paramSmoothing;
    static const char* paramOutput;

private:
    void runUntil (int& done, AudioSampleBuffer& buffer, int pos);
    
    int lastNote = -1;
    int velocity = 0;
    float last = 0;
    Array<int> noteQueue;
    
    LinearSmoothedValue<float> outputSmoothed;
    Component::SafePointer<VocAudioProcessorEditor> editor;
    
    voc_state* voc = nullptr;
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (VocAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
