/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class VocAudioProcessorEditor  : public gin::ProcessorEditor
{
public:
    VocAudioProcessorEditor (VocAudioProcessor&);
    ~VocAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;
    void paint (juce::Graphics& g) override;

    VocAudioProcessor& proc;
    
    gin::TriggeredScope scope {proc.fifo};
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (VocAudioProcessorEditor)
};

