/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "BinaryData.h"

using namespace gin;

//==============================================================================
VocAudioProcessorEditor::VocAudioProcessorEditor (VocAudioProcessor& p)
    : GinAudioProcessorEditor (p), processor (p)
{
    additionalProgramming = "Neil Thapen";
    
    logo = ImageFileFormat::loadFrom (BinaryData::logo_png, BinaryData::logo_pngSize);
    
    for (Parameter* pp : p.getPluginParameters())
    {
        ParamComponent* c = pp->isOnOff() ? (ParamComponent*)new Switch (pp) : (ParamComponent*)new Knob (pp);
        
        addAndMakeVisible (c);
        controls.add (c);
    }
    
    addAndMakeVisible (&scope);
    
    setGridSize (5, 2);
    
    scope.setNumSamplesPerPixel (2);
    scope.setVerticalZoomFactor (3.0f);

    p.setEditor (this);
}

VocAudioProcessorEditor::~VocAudioProcessorEditor()
{
    processor.setEditor (nullptr);
}

//==============================================================================
void VocAudioProcessorEditor::paint (Graphics& g)
{
    GinAudioProcessorEditor::paint (g);
        
    g.drawImageAt (logo, getWidth() / 2 - logo.getWidth() / 2, 0);
}

void VocAudioProcessorEditor::resized()
{
    using AP = VocAudioProcessor;
    
    GinAudioProcessorEditor::resized();
    
    Rectangle<int> r = getControlsArea();
    
    componentForId (AP::paramTenseness)->setBounds (getGridArea (0, 0));
    componentForId (AP::paramSmoothing)->setBounds (getGridArea (0, 1));
    componentForId (AP::paramConstrictionPosition)->setBounds (getGridArea (1, 0));
    componentForId (AP::paramConstrictionAmount)->setBounds (getGridArea (1, 1));
    
    componentForId (AP::paramOutput)->setBounds (getGridArea (4, 1));

    scope.setBounds (getGridArea (2, 0, 2, 2).reduced (5));
}
